import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TopBar } from "@/components/shared/TopBar"
import { LeftBar } from "@/components/shared/LeftBar"
import { RightBar } from "@/components/shared/RightBar"
import { BottomBar } from "@/components/shared/BottomBar"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app, version right before database",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        </head>
        <body>
        <TopBar/>
        <main>
          <LeftBar/>
          {children}
          <RightBar/>
        </main>
        <BottomBar/>
        </body>
      </html>
    </ClerkProvider>
  );
}
